plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.gmkbenjamin.gitrepo.beta'
    compileSdk 35

    defaultConfig {
        applicationId "io.github.gmkbenjamin.gitrepo.beta"
        minSdk 21
        targetSdk 35
        versionCode 8
        versionName "0.02"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.txt'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += [
                    'META-INF/LICENSE.txt',
                    'META-INF/NOTICE.txt',
                    'META-INF/DEPENDENCIES',
                    'META-INF/LICENSE',
                    'META-INF/NOTICE'
            ]
        }
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.fragment:fragment:1.8.5'
    implementation 'androidx.viewpager:viewpager:1.0.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.preference:preference:1.2.1'

    implementation 'com.j256.ormlite:ormlite-android:5.1'
    implementation 'com.j256.ormlite:ormlite-core:5.1'

    implementation 'org.apache.sshd:sshd-core:0.14.0'
    implementation 'org.apache.mina:mina-core:2.0.9'
    implementation 'org.eclipse.jgit:org.eclipse.jgit:3.7.1.201504261725-r'
    implementation 'commons-validator:commons-validator:1.7'
    implementation 'org.bouncycastle:bcprov-jdk15on:1.70'
}
